### DISCUSSION TITLE
How to use Ingress for SIP Card connections

### DISCUSSION THREAD

**Discussion by Whytey** [TECH7Fox/asterisk-hass-addons#375] [General]
Hi,

I have seen the addition of Ingress to the add-on and the update to the SIP card to utilise that addition.  Is there anything we need to do to configure this on either end?  

I was expecting this will allow us to utilise the card without having to temporarily accept the Asterix certificate we need to do at https://tech7fox.github.io/sip-hass-docs/docs/tutorial/card#manual and perhaps use the SIP client when remote from my home without port forwarding.  Would that be right?

Thanks,
Whytey

**Comment by TECH7Fox** [comment]
Hi, yes this is true. You don't need to set up ssl for Asterisk, and don't need to port forward the websocket connection. You may still need to forward RTP ports (10000-20000) if you encounter issues though.

To use ingress, simply upgrade the add-on and card to the latest versions and it should automatically detect it.

Let me know if it works 😁

**Reply by Whytey** [reply]
I am accessing home assistant via my nabu casa URL but I am internal to my LAN.  I am not able to connect to Asterix from the SIP card:

```
WebSocket connection to 'wss://192.168.0.80:8089/ws' failed:           WebSocketInterface.js:82
Connecting to wss://192.168.0.80:8089/ws                                 sipjs-card.ts:754 
ICE config: undefined                                                        sipjs-card.ts:789
```

This is my card config:
```
type: custom:sipjs-card
server: 192.168.0.80
port: "8089"
prefix: ""
button_size: "48"
state_color: true
auto_answer: false
hide_me: true
custom_title: ""
video: true
iceTimeout: 5
custom:
  - name: Doorbell
    number: "555"
    icon: mdi:doorbell
extensions:
  - person: person.david
    name: David
    extension: 100
    secret: 1234
    entity: sensor.100_state
  - person: person.megan
    name: Megan
    extension: 101
    secret: 1234
    entity: sensor.101_state
  - person: person.downstairs_tablet
    name: Downstairs
    extension: 103
    secret: 1234
    entity: sensor.103_state
dtmfs: []
buttons: []
```

Any help is appreciated.
