### ISSUE TITLE
Help needed: Install addon with docker-compose (without supervisor)

### ISSUE THREAD

**Issue by netsoft-ruidias** [TECH7Fox/asterisk-hass-addons#308]
Hello, 
I'm trying to use this addon in my setup, using `docker-compose` instead of supervisor (so, Ir can't be installed as a "normal" addon)

My `docker-compose.yaml` configuration file looks like this:
```yaml
version: '3.9'
services:
  homeassistant:
     (...)

  asterisk:
    container_name: asterisk
    image: ghcr.io/tech7fox/asterisk-hass-addon:main
    build:
      context: ./asterisk
    tty: true
    network_mode: host
    environment:
      # Required to get the list of persons from Home Assistant
      HA_TOKEN: "--REDACTED--"
    volumes:
      - /srv/homeassistant/config/asterisk:/config
      - /srv/homeassistant/config/www/sounds:/media
      - /etc/letsencrypt/live/certs:/ssl
    restart: unless-stopped
```

When I start the services, it creates the folders `asterisk/custom` and `asterisk/default` (inside my `asterisk` folder) but they are empty.

and logs:

```console
asterisk  | s6-rc: info: service s6rc-oneshot-runner: starting
asterisk  | s6-rc: info: service s6rc-oneshot-runner successfully started
asterisk  | s6-rc: info: service base-addon-banner: starting
asterisk  | s6-rc: info: service base-addon-banner successfully started
asterisk  | s6-rc: info: service fix-attrs: starting
asterisk  | s6-rc: info: service base-addon-timezone: starting
asterisk  | s6-rc: info: service base-addon-log-level: starting
asterisk  | s6-rc: info: service base-addon-log-level successfully started
asterisk  | s6-rc: info: service fix-attrs successfully started
asterisk  | [12:21:18] INFO: Configuring timezone (None)...
asterisk  | s6-rc: info: service base-addon-timezone successfully started
asterisk  | s6-rc: info: service legacy-cont-init: starting
asterisk  | cont-init: info: running /etc/cont-init.d/asterisk.sh
asterisk  | [12:21:19] INFO: Configuring certificate...
asterisk  | [12:21:19] INFO: Generating a self-signed certificate...
asterisk  | --REDACTED--
asterisk  | --REDACTED--
asterisk  | -----
asterisk  | [12:21:21] INFO: Generating Asterisk config files from add-on configuration...
asterisk  | [12:21:21] FATAL: 'ami_password' must be set
asterisk  | cont-init: info: /etc/cont-init.d/asterisk.sh exited 1
asterisk  | cont-init: warning: some scripts exited nonzero
asterisk  | s6-rc: warning: unable to start service legacy-cont-init: command exited 1
asterisk  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
asterisk  | /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
asterisk  | s6-rc: info: service fix-attrs: stopping
asterisk  | s6-rc: info: service base-addon-timezone: stopping
asterisk  | s6-rc: info: service base-addon-log-level: stopping
asterisk  | s6-rc: info: service base-addon-timezone successfully stopped
asterisk  | s6-rc: info: service fix-attrs successfully stopped
asterisk  | s6-rc: info: service base-addon-log-level successfully stopped
asterisk  | s6-rc: info: service base-addon-banner: stopping
asterisk  | s6-rc: info: service base-addon-banner successfully stopped
asterisk  | s6-rc: info: service s6rc-oneshot-runner: stopping
asterisk  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
asterisk exited with code 0
```

This line caught my attention `[12:21:21] FATAL: 'ami_password' must be set` so I realized that the `config.yaml` file must be missing, I searched this repository and found that file.

First I copied it to the `custom` folder with no effect, 
Then I copied it to the `default` folder, again with no effect,
I even copied it to the parent `asterisk`" folder, but I can't get it to work.

I've already researched and can't find the reason.
What I'm missing here?

Some help would be appreciated, 
thanks.
