### ISSUE TITLE
BUG: Can't edit the allowed networks for Manager login

### ISSUE THREAD

**Issue by netsoft-ruidias** [TECH7Fox/asterisk-hass-addons#310]
I'm reopening [this issue](https://github.com/TECH7Fox/asterisk-hass-addons/issues/309) again (I can't reopen the original) because I have news and there is actually a BUG that must be fixed.

> [!NOTE] 
> For more context on what's going on, take a look at the original issue:
> https://github.com/TECH7Fox/asterisk-hass-addons/issues/309

1. If I use `docker-compose down` and then `docker-compose up -d` then everything works as expected and the file is not changed back to defaults;
2. If I use `docker-compose restart` the file IS ACTUALLY rewritten with the default values, losing all customizations;
3. If I have a power outage, when the container starts, the file IS ACTUALLY rewritten with the default values, losing all customizations.

✔️ The first point is (obviously) not a problem because it is the expected behavior
✖️ The second point is a problem but there is a workaround, don't run that command
❌ The third point is a MAJOR problem and happens because docker compose is a service that starts at machine startup, and the container definition declares `restart: unless-stopped`

For context, this is my docker-compose yaml:
```yaml
version: '3.9'
services:
  (...)other services(...)

  asterisk:
    container_name: asterisk
    image: ghcr.io/tech7fox/asterisk-hass-addon:main
    build:
      context: ./asterisk
    tty: true
    network_mode: host
    environment:
      TZ: 'Europe/Lisbon'
      # Required to get the list of persons from Home Assistant
      HA_TOKEN: "--REDACTED--"
      HA_URL: 'https://xxxx.xxx.com'
    dns:
      - 192.168.1.2
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /srv/homeassistant/config/asterisk:/config
      - /srv/homeassistant/config/www/sounds:/media
      - /srv/homeassistant/config/ssl:/ssl
    restart: unless-stopped

  (...)other services(...)
```
