### ISSUE TITLE
No conifg.json file in ~/config/

### ISSUE THREAD

**Issue by sayam93** [TECH7Fox/asterisk-hass-addons#319]
I installed this in a docker container using a docker compose file on my Raspberry Pi 4B with the latest Home Assistant (2024.4.2) running in a container.

My docker-compose.yml looks like below:

```
services:
  asterisk:
    container_name: asterisk
    image: ghcr.io/tech7fox/asterisk-hass-addon:latest
    build:
      context: ~/asterisk
    tty: true
    network_mode: host
    restart: unless-stopped
    environment:
      HA_TOKEN: "tokegoeshere"
      HA_URL: "http://LOCALIP:8123"
    volumes:
      - ~/ha/config:/config
      - ~/ha/config/media:/media
```

However, there exists no configuration file in ~/config/asterisk/default/ (the folder exists with proper permissions) after the container is created and running using 'sudo docker compose up -d'.

I am trying to add an SIP card using this tutorial:

https://tech7fox.github.io/sip-hass-docs/docs/tutorial/add-on

What am I doing wrong? Please help!

**Comment by felipecrs** [comment]
Why tty: true?

**Comment by sayam93** [comment]
copied it from a sample docker-compose file

**Comment by felipecrs** [comment]
Remove it then, and try again.

Also share some logs.

**Comment by sayam93** [comment]
> Remove it then, and try again.
> 
> Also share some logs.

Removed but still the same.

Did exactly the below in cli and removed the tty=yes

<img width="568" alt="Screenshot 2024-04-10 at 6 38 02 AM" src="https://github.com/TECH7Fox/asterisk-hass-addons/assets/163408168/021e6d72-674c-4b16-8467-58b224a5272f">

```
services:
  asterisk:
    container_name: asterisk
    image: ghcr.io/tech7fox/asterisk-hass-addon:latest
    build:
      context: ~/asterisk
    tty: true
    network_mode: host
    restart: unless-stopped
    environment:
      HA_TOKEN: "tokegoeshere"
      HA_URL: "http://LOCALIP:8123"
    volumes:
      - ~/ha/config:/config
      - ~/ha/config/media:/media
```
Still no config files in the ~/config/asterisk/default/ folder
