### ISSUE TITLE
Cannot start in container mode

### ISSUE THREAD

**Issue by Suxsem** [TECH7Fox/asterisk-hass-addons#324]
I'm trying to run the addon in docker compose.

It seems that is not loading my config.json, everytime I try to start it I get:

```
root-asterisk-1  | [09:22:00] INFO: Configuring certificate...
root-asterisk-1  | [09:22:00] INFO: Using existing certificate as 'generate_ssl_certificate' is disabled...
root-asterisk-1  | [09:22:00] FATAL: Certificate file at /ssl/null was not found
```

This is my docker-compose

```
    asterisk:
        image: ghcr.io/tech7fox/amd64-addon-asterisk:latest
        network_mode: host
        tty: true
        environment:
        # Required to get the list of persons from Home Assistant
            HA_TOKEN: "redacted"
        volumes:
            - ./asterisk/config:/config
            - ./asterisk/media:/media
```

and this is my config.json

```
{
  "ami_password": null,
  "video_support": false,
  "auto_add": false,
  "auto_add_secret": "",
  "generate_ssl_cert": true,
  "certfile": "/config/ssl/fullchain.pem",
  "keyfile": "/config/ssl/privkey.pem",
  "additional_sounds": [],
  "mailbox": false,
  "mailbox_port": 12345,
  "mailbox_password": "",
  "mailbox_extension": "100",
  "mailbox_google_api_key": "",
  "log_level": "info"
}
```

Any help? thank you
