### ISSUE TITLE
Generate a call from HA ?

### ISSUE THREAD

**Issue by vincegre** [TECH7Fox/asterisk-hass-addons#329]
Hi

I'm trying to generate a call programmatically from HA but it works half way ! I can generate the call but it's always displayed as coming from Anonymous and not the extension I have setup in the service call as below. Both extensions 100 and 100 are well registered in system. Any ideas what's wrong there ? or is it a limitation of the addon ?

```
service: asterisk.send_action
data:
  action: Originate
  parameters:
    channel: PJSIP/100
    context: default
    exten: "101"
    priority: "1"
    caller_id: Home Assistant
    timeout: 60000
```

Thanks

Vincèn
