### ISSUE TITLE
Error in home assistant companion app when running add on

### ISSUE THREAD

**Issue by BjornPython** [TECH7Fox/asterisk-hass-addons#346]
When I open the HA companion app in my phone, I get this error:

![456592560_547524280939888_5447186701484803292_n](https://github.com/user-attachments/assets/bad81980-ce5f-43ff-a464-c06dadebbe87)

# to reproduce: 
- use nabu casa
- follow guide from official docs
- have `generate_ssl_cert` set to true
- start add on
- open HA companion app using `https URL from nabu casa`/`http:<HA IP here>:8123`

# there is no error when:
- the add on is not started
- I am using the chrome browser app (accepted the ssl cert  https://<HA IP>:8089/ws )
- fully kiosk browser lockdown with its setting `ignore SSL errors` turned on

my configuration file for the add on:
```yaml
ami_password: password
auto_add: true
auto_add_secret: password
video_support: true
generate_ssl_cert: true
certfile: fullchain.pem
keyfile: privkey.pem
additional_sounds: []
mailbox: false
mailbox_port: 12345
mailbox_password: password
mailbox_extension: "100"
mailbox_google_api_key: my-google-stt-key
log_level: info

```
